# Generated by Django 6.1.1 on 2026-10-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_level_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'db_table': 'grade_level',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('file_type', models.CharField(help_text='e.g., PDF, DOCX, PNG', max_length=50)),
                ('file_size_kb', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_offline_cached', models.BooleanField(default=False, help_text='Priority flag for Flutter offline download engine')),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='LessonGradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_content_standard', models.TextField(blank=True, null=True)),
                ('i_performance_standard', models.TextField(blank=True, null=True)),
                ('i_competencies_codes', models.TextField(blank=True, null=True)),
                ('i_objectives', models.TextField(blank=True, null=True)),
                ('l_context', models.TextField(blank=True, null=True)),
                ('w_reflection_questions', models.TextField(blank=True, null=True)),
                ('re_remediation', models.TextField(blank=True, null=True)),
                ('re_enrichment', models.TextField(blank=True, null=True)),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.gradelevel')),
            ],
            options={
                'db_table': 'lesson_grade_level',
            },
        ),
        migrations.CreateModel(
            name='LessonFlow',
            fields=[
                ('lf_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_minutes', models.IntegerField()),
                ('stage', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lesson_grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='curriculum.lessongradelevel')),
            ],
            options={
                'db_table': 'lesson_flow',
            },
        ),
        migrations.CreateModel(
            name='LessonGrading',
            fields=[
                ('lg_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('grade_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_score', models.IntegerField(default=100)),
                ('lesson_grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_tasks', to='curriculum.lessongradelevel')),
            ],
            options={
                'db_table': 'lesson_grading',
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('lp_id', models.AutoField(primary_key=True, serialize=False)),
                ('lp_title', models.CharField(max_length=255)),
                ('learning_area', models.CharField(max_length=100)),
                ('primary_language', models.CharField(max_length=50)),
                ('suggested_demographic', models.CharField(blank=True, max_length=255, null=True)),
                ('learning_model_description', models.TextField(blank=True, null=True)),
                ('intentions_description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('grade_levels', models.ManyToManyField(related_name='lesson_plans', through='curriculum.LessonGradeLevel', to='curriculum.gradelevel')),
            ],
            options={
                'db_table': 'lesson_plan',
            },
        ),
        migrations.AddField(
            model_name='lessongradelevel',
            name='lp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lessonplan'),
        ),
        migrations.CreateModel(
            name='LpAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(default='Primary Author', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lessonplan')),
            ],
            options={
                'db_table': 'lp_author',
                'unique_together': {('lp', 'account')},
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='authors',
            field=models.ManyToManyField(related_name='authored_lesson_plans', through='curriculum.LpAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LpChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_role', models.CharField(default='Reviewer', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lessonplan')),
            ],
            options={
                'db_table': 'lp_checker',
                'unique_together': {('lp', 'account')},
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='checkers',
            field=models.ManyToManyField(related_name='checked_lesson_plans', through='curriculum.LpChecker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LessonGradeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_instructions', models.TextField(blank=True, null=True)),
                ('lesson_grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lessongradelevel')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.material')),
            ],
            options={
                'db_table': 'lesson_grade_material',
                'unique_together': {('lesson_grade_level', 'material')},
            },
        ),
        migrations.AddField(
            model_name='lessongradelevel',
            name='materials',
            field=models.ManyToManyField(related_name='lesson_grade_levels', through='curriculum.LessonGradeMaterial', to='curriculum.material'),
        ),
        migrations.AlterUniqueTogether(
            name='lessongradelevel',
            unique_together={('lp', 'gl')},
        ),
    ]
