# Generated by Django 6.1.1 on 2026-10-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('school_location', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session_time', models.CharField(max_length=100)),
                ('lp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='curriculum.lessonplan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_fname', models.CharField(max_length=100)),
                ('student_lname', models.CharField(max_length=100)),
                ('student_mi', models.CharField(blank=True, max_length=5, null=True)),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='curriculum.gradelevel')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('student_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_absent', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.student')),
            ],
            options={
                'db_table': 'student_class',
                'unique_together': {('clazz', 'student')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', through='classrooms.StudentClass', to='classrooms.student'),
        ),
        migrations.CreateModel(
            name='StudentGrading',
            fields=[
                ('sg_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='curriculum.lessongrading')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classrooms.studentclass')),
            ],
            options={
                'db_table': 'student_grading',
                'unique_together': {('lg', 'student_class')},
            },
        ),
    ]
